version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/postgres:11
        environment:
          POSTGRES_USER: admin
          POSTGRES_DB: developer
    working_directory: ~/git/developer-test
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn integration-test
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
